{
 "title": "hri-flink-dashboard",
 "description": "Dashboard to monitor Flink metrics with Prometheus",
 "tags": [ "hri-flink" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info{namespace=~\"cdt-payer-landing-ns-0.*\"}, namespace)"
   },
   { "name": "job_name", "query": "label_values(job_name)" },
   {
    "name": "pod",
    "query": "label_values(kube_pod_container_info{namespace=\"$namespace\"},pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "No. of Taskmanagers",
     "type": "gauge",
     "description": "No. of Taskmanagers",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "flink_jobmanager_numRegisteredTaskManagers{kubernetes_namespace=~\"$namespace\"}",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Number of Task Slots Available",
     "type": "stat",
     "description": "Number of Task Slots Available",
     "gridPos": { "h": 3, "w": 5, "x": 6, "y": 1 },
     "targets": [
      {
       "expr": "flink_jobmanager_taskSlotsAvailable{kubernetes_namespace=~\"$namespace\"}",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Total Number of Running Jobs",
     "type": "bargauge",
     "description": "Total Number of Running Jobs",
     "gridPos": { "h": 3, "w": 13, "x": 11, "y": 1 },
     "targets": [
      {
       "expr": "flink_jobmanager_numRunningJobs{kubernetes_namespace=~\"$namespace\"}",
       "legendFormat": "{{app}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU/Memory Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "JobManager - CPU Load (%)",
     "type": "graph",
     "description": "JobManager - recent CPU usage of the JVM (%)",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_CPU_Load{kubernetes_namespace=~\"$namespace\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "TaskManager - CPU Load (%)",
     "type": "graph",
     "description": "TaskManager - recent CPU usage of the JVM (%)",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_CPU_Load{kubernetes_namespace=~\"$namespace\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "JobManager Memory Used",
     "type": "graph",
     "description": "JobManager - amount of memory used by the JVM for the direct buffer pool",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Direct_MemoryUsed{kubernetes_namespace=~\"$namespace\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "TaskManager Memory Used",
     "type": "graph",
     "description": "TaskManager - amount of memory used by the JVM for the direct buffer pool",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Direct_MemoryUsed{kubernetes_namespace=~\"$namespace\"}",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Job Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of records received",
     "type": "graph",
     "description": "The total number of records this operator/task has received.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_numRecordsIn{kubernetes_namespace=~\"$namespace\",job_name=~\"$job_name\"})",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Number of records processed",
     "type": "graph",
     "description": "The total number of records this operator/task has emitted.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_numRecordsOut{kubernetes_namespace=~\"$namespace\",job_name=~\"$job_name\"})",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "No. records In per second",
     "type": "graph",
     "description": "The number of records this operator/task receives per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_numRecordsInPerSecond{kubernetes_namespace=~\"$namespace\",job_name=~\"$job_name\"})",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "No. records out per second",
     "type": "graph",
     "description": "The number of records this operator/task sends per second",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_numRecordsOutPerSecond{kubernetes_namespace=~\"$namespace\",job_name=~\"$job_name\"})",
       "legendFormat": "{{app}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Checkpoint Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Checkpoints in Progress",
     "type": "graph",
     "description": "The number of in progress checkpoints.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "flink_jobmanager_job_numberOfInProgressCheckpoints{kubernetes_namespace=~\"$namespace\",job_name=~\"$job_name\"}",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Completed Checkpoints",
     "type": "graph",
     "description": "The number of successfully completed checkpoints.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_jobmanager_job_numberOfCompletedCheckpoints{kubernetes_namespace=~\"$namespace\",job_name=~\"$job_name\"})",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Failed Checkpoints",
     "type": "graph",
     "description": "The number of failed checkpoints.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_jobmanager_job_numberOfFailedCheckpoints{kubernetes_namespace=~\"$namespace\",job_name=~\"$job_name\"})",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Total Checkpoints",
     "type": "graph",
     "description": "The number of total checkpoints (in progress, completed, failed).",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flink_jobmanager_job_totalNumberOfCheckpoints{kubernetes_namespace=~\"$namespace\",job_name=~\"$job_name\"})",
       "legendFormat": "{{app}}"
      }
     ]
    }
   ]
  }
 ]
}